version: "3.8"

services:
  postgresql:
    image: postgres:13
    container_name: app-postgresql
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: app-redis
    restart: always
    env_file:
      - ./.env
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: app-rabbitmq
    restart: always
    env_file:
      - ./.env
    environment:
      - RABBITMQ_MANAGEMENT_PATH_PREFIX=/rabbitmq
    ports:
      - "0.0.0.0:5672:5672" # AMQP
      - "127.0.0.1:15672:15672" # Management UI (로컬 바인딩)
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro # 호스트의 rabbitmq.conf 를 컨테이너 설정 파일로 마운트

    networks:
      - app-network

  # ──────────────────────────────────────────────
  # ▶ Monitoring Stack
  # ──────────────────────────────────────────────

  prometheus:
    image: prom/prometheus:v2.47.0
    container_name: monitor-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/alarm.rules.yml:/etc/prometheus/alarm.rules.yml:ro
    ports:
      - "9090:9090"
    networks:
      - app-network

  alertmanager:
    image: prom/alertmanager:v0.25.0
    container_name: monitor-alertmanager
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
    ports:
      - "9093:9093"
    networks:
      - app-network

  grafana:
    image: grafana/grafana:10.2.0
    container_name: monitor-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=gngnqnfauswmds303
    ports:
      - "3001:3000"
    networks:
      - app-network
    depends_on:
      - prometheus

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.4.2
    container_name: monitor-nginx-exporter
    command:
      - -nginx.scrape-uri
      - http://nginx:9113/nginx_status
    ports:
      - "9114:9114"
    networks:
      - app-network

  cadvisor:
    image: google/cadvisor:latest
    container_name: monitor-cadvisor
    ports:
      - "8085:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:

networks:
  app-network:
    external: true
