import 'package:sleep_tight/core/data/models/enums/error_code.dart';
import 'package:dio/dio.dart';

class ApiException implements Exception {
  /// The primary error message, intended for user display or logging.
  final String message;

  /// The HTTP status code from the server response (e.g., 400, 401, 500).
  final int? httpStatusCode;

  /// Application-specific error code from the backend (e.g., 'USER_NOT_FOUND', 'TOKEN_EXPIRED').
  final String? apiErrorCode;

  /// The original error data received from the server or generated by Dio.
  /// Useful for debugging or extracting further details.
  final dynamic errorData;

  ApiException({
    required this.message,
    this.httpStatusCode,
    this.apiErrorCode,
    this.errorData,
  });

  factory ApiException.fromDioError(DioException dioError) {
    // If dioError.error is already an ApiException (e.g., processed by interceptor's onResponse), return it.
    if (dioError.error is ApiException) {
      return dioError.error as ApiException;
    }

    String finalMessage = '알 수 없는 오류가 발생했습니다.';
    int? finalHttpStatusCode = dioError.response?.statusCode;
    String? finalApiErrorCode;
    dynamic originalErrorData = dioError.response?.data;

    if (originalErrorData is Map<String, dynamic>) {
      if (originalErrorData.containsKey('success') &&
          originalErrorData['success'] == false &&
          originalErrorData['data'] is Map<String, dynamic>) {
        final apiErrorPayload =
            originalErrorData['data'] as Map<String, dynamic>;

        final String backendErrorCodeString =
            apiErrorPayload['code'] as String? ?? 'UNKNOWN_ERROR';
        final ErrorCode errorCode = ErrorCode.fromCode(backendErrorCodeString);

        finalMessage = errorCode.message; // ErrorCode enum에서 직접 메시지 가져오기
        finalApiErrorCode = errorCode.code; // ErrorCode enum에서 직접 코드 문자열 가져오기
      }
    }

    // If not fully parsed from a structured JSON error (e.g., apiErrorCode is still null,
    // or message is still a generic default from ApiError),
    // determine message and code from DioExceptionType or HTTP status code.
    if (finalApiErrorCode == null ||
        finalMessage == '알 수 없는 오류가 발생했습니다.' ||
        finalMessage == '에러가 발생했습니다.') {
      switch (dioError.type) {
        case DioExceptionType.connectionTimeout:
          finalMessage = '서버 연결 시간이 초과되었습니다.';
          finalApiErrorCode = finalApiErrorCode ?? 'CONNECTION_TIMEOUT';
          break;
        case DioExceptionType.sendTimeout:
          finalMessage = '요청 전송 시간이 초과되었습니다.';
          finalApiErrorCode = finalApiErrorCode ?? 'SEND_TIMEOUT';
          break;
        case DioExceptionType.receiveTimeout:
          finalMessage = '응답 수신 시간이 초과되었습니다.';
          finalApiErrorCode = finalApiErrorCode ?? 'RECEIVE_TIMEOUT';
          break;
        case DioExceptionType.badResponse:
          // If finalMessage is still generic (not from a parsed ApiError), use _handleStatusCode.
          if (finalMessage == '알 수 없는 오류가 발생했습니다.' ||
              finalMessage == '에러가 발생했습니다.') {
            finalMessage = _handleStatusCode(
              finalHttpStatusCode,
              originalErrorData,
            );
          }
          // finalApiErrorCode might have been set from JSON. If not, use HTTP status as part of the code.
          finalApiErrorCode =
              finalApiErrorCode ?? 'HTTP_${finalHttpStatusCode ?? 'UNKNOWN'}';
          break;
        case DioExceptionType.cancel:
          finalMessage = 'API 요청이 취소되었습니다.';
          finalApiErrorCode = finalApiErrorCode ?? 'REQUEST_CANCELLED';
          break;
        case DioExceptionType.connectionError: // For Dio 5.x
          finalMessage = '네트워크 연결 오류가 발생했습니다. 인터넷 연결을 확인해주세요.';
          finalApiErrorCode = finalApiErrorCode ?? 'CONNECTION_ERROR';
          break;
        case DioExceptionType.unknown:
        default:
          if (dioError.message?.contains('SocketException') ?? false) {
            finalMessage = '인터넷에 연결할 수 없습니다. 네트워크 상태를 확인해주세요.';
            finalApiErrorCode = finalApiErrorCode ?? 'NO_INTERNET';
          } else if (originalErrorData is String &&
              originalErrorData.isNotEmpty) {
            // If the error data itself is a simple string message
            finalMessage = originalErrorData;
            finalApiErrorCode = finalApiErrorCode ?? 'UNKNOWN_STRING_ERROR';
          } else {
            finalMessage = dioError.message ?? '예기치 않은 오류가 발생했습니다.';
            finalApiErrorCode = finalApiErrorCode ?? 'UNEXPECTED_ERROR';
          }
          break;
      }
    }

    return ApiException(
      message: finalMessage,
      httpStatusCode: finalHttpStatusCode,
      apiErrorCode: finalApiErrorCode,
      errorData: originalErrorData,
    );
  }

  /// Provides a generic error message based on HTTP status code.
  /// This is a fallback if the server response doesn't contain a specific message
  /// or if the error is not a structured JSON error.
  static String _handleStatusCode(int? statusCode, dynamic errorBody) {
    // If errorBody is a Map and contains a 'message', prefer that.
    if (errorBody is Map<String, dynamic> &&
        errorBody.containsKey('message') &&
        errorBody['message'] is String) {
      final potentialMessage = errorBody['message'] as String;
      if (potentialMessage.isNotEmpty) return potentialMessage;
    }
    // If errorBody itself is a non-empty string, use it.
    if (errorBody is String && errorBody.isNotEmpty) {
      return errorBody;
    }

    // Fallback to generic messages based on Backend ExceptionCode patterns
    switch (statusCode) {
      case 400:
        return '잘못된 요청입니다. (400)';
      case 401:
        return '인증 정보가 유효하지 않거나 필요합니다. (401)';
      case 402:
        return '토큰이 만료되었습니다. (402)';
      case 403:
        return '접근 권한이 없습니다. (403)';
      case 404:
        return '요청하신 정보를 찾을 수 없습니다. (404)';
      case 409:
        return '요청이 서버의 현재 상태와 충돌합니다. (409)';
      case 422:
        return '처리할 수 없는 요청입니다. 입력값을 확인해주세요. (422)';
      case 499: // NestJS 'REFRESH_TOKEN_*' errors
        return '토큰 갱신 중 문제가 발생했습니다. (499)';
      case 500:
        return '서버 내부 오류가 발생했습니다. 잠시 후 다시 시도해주세요. (500)';
      case 502:
        return '게이트웨이 오류가 발생했습니다. (502)';
      case 503:
        return '서버가 일시적으로 요청을 처리할 수 없습니다. (503)';
      default:
        return '알 수 없는 서버 오류가 발생했습니다. (상태 코드: ${statusCode ?? 'N/A'})';
    }
  }

  @override
  String toString() {
    return 'ApiException: $message (HTTP Status: $httpStatusCode, API Code: $apiErrorCode, Data: $errorData)';
  }
}
